on: [push]

name: build

jobs:
  test:
    name: Rust project

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: miri

      - name: Build default
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Build nostd
        run: cargo build --no-default-features

      - name: Build all features
        run: cargo build --all-features

      - name: Test with Miri
        run: cargo miri test
